name: ivmodels
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.7
  - numpy
  - pytest  # tests only
  - scikit-learn
  - glum
  - pandas  # optional
  - sphinx  # docs
  - sphinxcontrib-apidoc  # docs
  - ipython  # docs
  - sphinx_rtd_theme  # docs
  - sphinxcontrib-bibtex  # docs
  - pip  # docs